name: Clock Out ðŸ••

on:
  schedule:
  - cron: 0 11 * * 1-5

concurrency:
  group: clockout
  cancel-in-progress: false

jobs:
  clockout:
    name: Clocking out ðŸ••
    uses: ./.github/workflows/runner.yml
    with:
      action: clockout
    secrets: inherit